---
title: "Tugas Praktikum"
author: "Muhammad Regi Abdi Putra Amanta"
date: "2024-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#instal packages terlebih dahulu
install.packages("tidyverse")
install.packages("DataExplorer")
install.packages("skimr")
```
```{r}
#panggil semua Librarynya
library(tidyverse)
library(DataExplorer)
library(skimr)
```

```{r}
#import dataset dari file excel yang telah disiapkan
data_house <- read.csv("C:/Users/Mahasiswa/Downloads/house_price1.csv",stringsAsFactors = TRUE)
glimpse(data_house)
```
```{r}
#Memeriksa Gambaran Umum data
plot_intro(data = data_house,

geom_label_args = list(size=2.5))

```
```{r}
#skim_without_charts merupakan fungsi yang berasal dari package skimr dan argumen utamanya
adalah object berbentuk data.frame.
skim_without_charts(data = data_house)
```
```{r}
data_house1 <- data_house %>%
select(-Id) %>%
mutate(
Alley = forcats::fct_explicit_na(Alley, na_level = "Ukn"),
FireplaceQu=forcats::fct_explicit_na(FireplaceQu,
na_level = "Ukn"
),

PoolQC = forcats::fct_explicit_na(PoolQC, na_level = "Ukn"),
Fence = forcats::fct_explicit_na(Fence, na_level = "Ukn"),
MiscFeature = forcats::fct_explicit_na(MiscFeature, na_level = "Ukn")
) %>% na.omit
```
```{r}
plot_intro(data = data_house1)
```
```{r}
skim_without_charts(data_house1)
```
```{r}
data_house1 <- data_house1 %>%
select(-Utilities)
```
```{r}
plot_histogram(data = data_house1,nrow=3,ncol = 3,

geom_histogram_args = list(fill="steelblue"),
ggtheme = theme_bw()
)
```
```{r}
plot_bar(data = data_house1,ggtheme =theme_bw(),nrow = 1)
```
```{r}
plot_scatterplot(data = data_house1 %>%
select_if(is.numeric),
by="SalePrice",geom_point_args = list(color="steelblue"),ggtheme = theme_bw() )
```
```{r}
cor_mat <- cor(data_house1%>%

select_if(is.numeric),method = "spearman")

cor_mat[upper.tri(cor_mat,diag = TRUE)] <- NA
cor_df <- cor_mat %>%
as.data.frame() %>%
rownames_to_column(var = "Var1") %>%
pivot_longer(names_to = "Var2",
values_to = "corr",
-Var1) %>% na.omit

cor_df %>% filter(abs(corr)>0.6) %>% arrange(desc(abs(corr)))
```
```{r}
cor_df %>% filter(abs(corr)<=0.6)
```
```{r}
cat_var_names <- data_house1 %>%
select(where(is.factor),SalePrice) %>%
names
cat_var_names
```
```{r}
for(i in cat_var_names[-43]){
plot_boxplot(data = data_house1 %>%

select(where(is.factor),SalePrice),
geom_boxplot_args=list(fill="steelblue"),
by=i,ggtheme = theme_bw())

}
```


